  // Define your audio file sources here
  const audioSources = {
    audio1: 'audio/aa_kimochiwarui.mp3',
    audio2: 'audio/adios.mp3',
    audio3: 'audio/ahoy.mp3',
    audio4: 'audio/alchohol_is_the_solution.mp3',
    audio5: 'audio/anyanyanyanya.mp3',
    audio6: 'audio/ararara.mp3',
    audio7: 'audio/arigatou.mp3',
    audio8: 'audio/arigatou2.mp3',
    audio9: 'audio/awnaaa.mp3',
    audio10: 'audio/awoooo.mp3',
    audio11: 'audio/baaaaananaaaaaaa.mp3',
    audio12: 'audio/bakabakabakabaka.mp3',
    audio13: 'audio/bakatareeee.mp3',
    audio14: 'audio/bakataregaaa.mp3',
    audio15: 'audio/bakudan.mp3',
    audio16: 'audio/banana.mp3',
    audio17: 'audio/bio.mp3',
    audio18: 'audio/lamy_giggles.mp3',
    audio19: 'audio/boingboing.mp3',
    audio20: 'audio/brabrabra.mp3',
    audio21: 'audio/buegheuehiehe.mp3',
    audio22: 'audio/buhibuhi.mp3',
    audio23: 'audio/buhiiiii.mp3',
    audio24: 'audio/catchyou.mp3',
    audio25: 'audio/catchyukimin.mp3',
    audio26: 'audio/chu.mp3',
    audio27: 'audio/confused_lamy.mp3',
    audio28: 'audio/cute_lamynglish.mp3',
    audio29: 'audio/cuteraishou.mp3',
    audio30: 'audio/dechata.mp3',
    audio31: 'audio/dokidoki.mp3',
    audio32: 'audio/dokodon.mp3',
    audio33: 'audio/dokodon2.mp3',
    audio34: 'audio/dooon.mp3',
    audio35: 'audio/doublesneeze.mp3',
    audio36: 'audio/doyukoto.mp3',
    audio37: 'audio/eheheh.mp3',
    audio38: 'audio/ehehehehehe.mp3',
    audio39: 'audio/evil_lamy_laugh.mp3',
    audio40: 'audio/full.mp3',
    audio41: 'audio/fumbling_lamy1.mp3',
    audio42: 'audio/fumbling_lamy2.mp3',
    audio43: 'audio/fun.mp3',
    audio44: 'audio/funafuna.mp3',
    audio45: 'audio/fuuuuu2.mp3',
    audio46: 'audio/gachang.mp3',
    audio47: 'audio/gagagaga.mp3',
    audio48: 'audio/good_dream_spell.mp3',
    audio49: 'audio/gotonextfloor.mp3',
    audio50: 'audio/gremlin_noise.mp3',
    audio51: 'audio/hai_nekochan.mp3',
    audio52: 'audio/happy_birthday1.mp3',
    audio53: 'audio/happy_birthday2.mp3',
    audio54: 'audio/happy_halloween.mp3',
    audio55: 'audio/hi.mp3',
    audio56: 'audio/hiahahahya.mp3',
    audio57: 'audio/hiiiiiscream.mp3',
    audio58: 'audio/mendokusai_lamy.mp3',
    audio59: 'audio/ht.mp3',
    audio60: 'audio/hyperharemtime.mp3',
    audio61: 'audio/lamy_ending_english.mp3',
    audio62: 'audio/ihihi.mp3',
    audio63: 'audio/Imouto_line.mp3',
    audio64: 'audio/Inscribe_pride_into_the_wood.mp3',
    audio65: 'audio/itai.mp3',
    audio66: 'audio/Itterashai.mp3',
    audio67: 'audio/jujutsu_kaisen.mp3',
    audio68: 'audio/kabe.mp3',
    audio69: 'audio/karakai.mp3',
    audio70: 'audio/kawaii.mp3',
    audio71: 'audio/kawaii3.mp3',
    audio72: 'audio/kawaii4.mp3',
    audio73: 'audio/kawaiilong.mp3',
    audio74: 'audio/kawayo.mp3',
    audio75: 'audio/kawayov2.mp3',
    audio76: 'audio/kimazui.mp3',
    audio77: 'audio/kimochi_warui_oji-san.mp3',
    audio78: 'audio/kimochiwarui.mp3',
    audio79: 'audio/kimoi.mp3',
    audio80: 'audio/kiss_me_baby.mp3',
    audio81: 'audio/kitanee.mp3',
    audio82: 'audio/kitanekitane.mp3',
    audio83: 'audio/kmcwr.mp3',
    audio84: 'audio/koitsunani.mp3',
    audio85: 'audio/kokuhaku.mp3',
    audio86: 'audio/konaide.mp3',
    audio87: 'audio/konlamy.mp3',
    audio88: 'audio/koreda.mp3',
    audio89: 'audio/koreio.mp3',
    audio90: 'audio/koremo_intensifies.mp3',
    audio91: 'audio/kusa.mp3',
    audio92: 'audio/kuuuu.mp3',
    audio93: 'audio/laaaaaaaaaaibura.mp3',
    audio94: 'audio/laibura.mp3',
    audio95: 'audio/laiburabura.mp3',
    audio96: 'audio/laliho.mp3',
    audio97: 'audio/lamy_moemoe_kyun.mp3',
    audio98: 'audio/lamy__eating_chips.mp3',
    audio99: 'audio/lamy_aaaa.mp3',
    audio100: 'audio/lamy_brrrr.mp3',
    audio101: 'audio/lamy_daisuki_dayo_chu.mp3',
    audio102: 'audio/lamy_daisuki_no_yukimins.mp3',
    audio103: 'audio/lamy_darling.mp3',
    audio104: 'audio/lamy_ehehehe.mp3',
    audio105: 'audio/Lamy_ending_its_me_with_many_kiss.mp3',
    audio106: 'audio/Lamy_eng.mp3',
    audio107: 'audio/Lamy_forget_mute_stretch.mp3',
    audio108: 'audio/lamy_hehe.mp3',
    audio109: 'audio/lamy_hey.mp3',
    audio110: 'audio/lamy_hi_honey.mp3',
    audio111: 'audio/lamy_hmm_kiss.mp3',
    audio112: 'audio/lamy_horn_noise.mp3',
    audio113: 'audio/lamy_leftxright.mp3',
    audio114: 'audio/lamy_mizu_oshi.mp3',
    audio115: 'audio/Lamy_Nice_Nature.mp3',
    audio116: 'audio/lamy_noises.mp3',
    audio117: 'audio/lamy_oh_no1.mp3',
    audio118: 'audio/lamy_oh_no2.mp3',
    audio119: 'audio/lamy_ohayooooo.mp3',
    audio120: 'audio/lamy_mama_scream.mp3',
    audio121: 'audio/lamy_stretching.mp3',
    audio122: 'audio/lamy_vacuum_kiss_with_laugh.mp3',
    audio123: 'audio/lamy_yawn.mp3',
    audio124: 'audio/lamy_yelling.mp3',
    audio125: 'audio/lamybreathing.mp3',
    audio126: 'audio/lamybreathing2.mp3',
    audio127: 'audio/lamybreathwheeze.mp3',
    audio128: 'audio/lamycutelong wheeze.mp3',
    audio129: 'audio/lamyened.mp3',
    audio130: 'audio/lamyeng.mp3',
    audio131: 'audio/lamyeng1.mp3',
    audio132: 'audio/lamyeng2.mp3',
    audio133: 'audio/lamyenglish.mp3',
    audio134: 'audio/lamy_hahaha.mp3',
    audio135: 'audio/lamy_pokemon_hum.mp3',
    audio136: 'audio/lamy_kirby.mp3',
    audio137: 'audio/lamylongwheeze.mp3',
    audio138: 'audio/lamynglish.mp3',
    audio139: 'audio/lamynoInu.mp3',
    audio140: 'audio/lamynoise1.mp3',
    audio141: 'audio/lamynoise2.mp3',
    audio142: 'audio/lamy_rooster.mp3',
    audio143: 'audio/lamyscream.mp3',
    audio144: 'audio/lamy_surprise_attack.mp3',
    audio145: 'audio/lamywheeze.mp3',
    audio146: 'audio/lamy_yell.mp3',
    audio147: 'audio/limited_edition.mp3',
    audio148: 'audio/maaaaa.mp3',
    audio149: 'audio/makaserori.mp3',
    audio150: 'audio/mama.mp3',
    audio151: 'audio/matemate.mp3',
    audio152: 'audio/may_you_all_have_blessing_today.mp3',
    audio153: 'audio/membershipsong.mp3',
    audio154: 'audio/meowthaaa2.mp3',
    audio155: 'audio/meowthaaaa.mp3',
    audio156: 'audio/mococo.mp3',
    audio157: 'audio/mooooo.mp3',
    audio158: 'audio/more_lamynglish.mp3',
    audio159: 'audio/mumumumumu.mp3',
    audio160: 'audio/muuuuuu.mp3',
    audio161: 'audio/my_nine.mp3',
    audio162: 'audio/naisu.mp3',
    audio163: 'audio/nananananaaanaaaaaaaaaaaaaaaa.mp3',
    audio164: 'audio/nanigasuki.mp3',
    audio165: 'audio/nani_nani_intensifiy.mp3',
    audio166: 'audio/naruhodo.mp3',
    audio167: 'audio/necchushou.mp3',
    audio168: 'audio/nekochaaaan.mp3',
    audio169: 'audio/nekochayntasukaru.mp3',
    audio170: 'audio/noooooo.mp3',
    audio171: 'audio/nyahallo_Lamy.mp3',
    audio172: 'audio/nyan.mp3',
    audio173: 'audio/nyatskr.mp3',
    audio174: 'audio/nyaunyaunyau.mp3',
    audio175: 'audio/oh_my_lamy.mp3',
    audio176: 'audio/oishooishooisho.mp3',
    audio177: 'audio/omedetou.mp3',
    audio178: 'audio/onakasuita.mp3',
    audio179: 'audio/osha.mp3',
    audio180: 'audio/otsulamy.mp3',
    audio181: 'audio/otsulamy_with_giggles2.mp3',
    audio182: 'audio/otsulamy_with_giggles1.mp3',
    audio183: 'audio/overseasbros_english.mp3',
    audio184: 'audio/oyasuminasai.mp3',
    audio185: 'audio/panik_lamy.mp3',
    audio186: 'audio/piaaaaaa.mp3',
    audio187: 'audio/please_like_and_subscribe.mp3',
    audio188: 'audio/please_wait_a_moment.mp3',
    audio189: 'audio/pokapoka.mp3',
    audio190: 'audio/pyonpyon.mp3',
    audio191: 'audio/pyonpyonpyonpyon.mp3',
    audio192: 'audio/pyuneeeee.mp3',
    audio193: 'audio/rainbowV1.mp3',
    audio194: 'audio/rainbowV2.mp3',
    audio195: 'audio/raisho.mp3',
    audio196: 'audio/rythm_heaven_kokoro.mp3',
    audio197: 'audio/rythm_heaven_nya.mp3',
    audio198: 'audio/sadwamy.mp3',
    audio199: 'audio/shinratsu.mp3',
    audio200: 'audio/shinratsuuu.mp3',
    audio201: 'audio/may_you_have_blessing_today.mp3',
    audio203: 'audio/lamy_short_horn.mp3',
    audio204: 'audio/shuuuuuuu.mp3',
    audio205: 'audio/sleepy_lamy.mp3',
    audio206: 'audio/soiukoto.mp3',
    audio207: 'audio/sorehasou.mp3',
    audio208: 'audio/sorry_sorry_SORRY.mp3',
    audio209: 'audio/sosososososo.mp3',
    audio210: 'audio/sosososososososoSO.mp3',
    audio211: 'audio/souhanaranyaro.mp3',
    audio212: 'audio/souhanaranyarov2.mp3',
    audio213: 'audio/stop_stooooop.mp3',
    audio214: 'audio/suimasen.mp3',
    audio215: 'audio/sukidai.mp3',
    audio216: 'audio/super_confuse_lamy.mp3',
    audio217: 'audio/suuuu-.mp3',
    audio218: 'audio/t_choichoichoichoichoichoi.mp3',
    audio219: 'audio/tatatatatan.mp3',
    audio220: 'audio/thundaga.mp3',
    audio221: 'audio/trick_or_treat1.mp3',
    audio222: 'audio/trick_or_treat2.mp3',
    audio223: 'audio/trick_or_treat3.mp3',
    audio224: 'audio/trick_or_treat4.mp3',
    audio225: 'audio/trick_or_treat5.mp3',
    audio226: 'audio/ugui.mp3',
    audio227: 'audio/uhyuoooo.mp3',
    audio228: 'audio/waaaaa.mp3',
    audio229: 'audio/waaaaaaaaaaaaaaaaaaa.mp3',
    audio230: 'audio/waaaaan.mp3',
    audio231: 'audio/wakaranai.mp3',
    audio232: 'audio/wakarimasen.mp3',
    audio233: 'audio/wakatakana.mp3',
    audio234: 'audio/wake_up_alarm.mp3',
    audio235: 'audio/wamy_mel_kun_suki.mp3',
    audio236: 'audio/wamy_sanshita.mp3',
    audio237: 'audio/wao.mp3',
    audio238: 'audio/wawawa.mp3',
    audio239: 'audio/wawawawawawa.mp3',
    audio240: 'audio/weeee.mp3',
    audio241: 'audio/what are you doing.mp3',
    audio242: 'audio/what_are_you_doing_in.mp3',
    audio243: 'audio/what_do_you_know_about_the.mp3',
    audio244: 'audio/what_is_this_place.mp3',
    audio245: 'audio/wuaaaaa.mp3',
    audio246: 'audio/yaaaa aaaa.mp3',
    audio247: 'audio/yamenaa1.mp3',
    audio248: 'audio/yamenaa2.mp3',
    audio249: 'audio/yamenaa3.mp3',
    audio250: 'audio/yamenaa4.mp3',
    audio251: 'audio/yamenazaio.mp3',
    audio252: 'audio/yarunka_yarannoka.mp3',
    audio253: 'audio/yatta.mp3',
    audio254: 'audio/yokozo.mp3',
    audio255: 'audio/yoroshiku.mp3',
    audio256: 'audio/yoyoyoyoyoyo.mp3',
    audio257: 'audio/yukihana_yagi.mp3'
  };

  // Keep track of the current audio being played
  let currentAudio = null;

  // Add event listeners to all buttons with data-audio attributes
  document.querySelectorAll('button[data-audio]').forEach(button => {
    button.addEventListener('click', () => {
      const key = button.dataset.audio;
      const src = audioSources[key];

      if (!src) {
        console.warn(`No audio source found for "${key}"`);
        return;
      }

      // Stop any currently playing audio
      if (currentAudio) {
        currentAudio.pause();
        currentAudio.currentTime = 0; // reset playback
      }

      // Create and play the new audio
      currentAudio = new Audio(src);
      currentAudio.play();
    });
  });